Validations
friendlyantz/who_is_america pull request #41
Opened 2021-04-11 08:58 UTC by friendlyantz

- [ ] basic validations for the models added
- [ ] https for source link custom validation

2021-04-11 21:01 UTC, friendlyantz commented
Master merged 12-APR. rdy to review

2021-04-14 07:57 UTC, StanislavLohtin requested changes

2021-04-14 10:07 UTC, friendlyantz commented
Great point, haven't thought about it. Happy if you remove this! Cheers

On Wed, Apr 14, 2021, 17:57 Stanislav Lohtin ***@***.***>
wrote:

> *@StanislavLohtin* requested changes on this pull request.
> ------------------------------
>
> In app/models/location.rb
> <https://github.com/friendlyantz/who_is_america/pull/41#discussion_r611246770>
> :
>
> > @@ -6,4 +6,6 @@ class Location < ApplicationRecord
>
>    enum location_type: [:country, :state, :city]
>
> +  validates :name, presence: true, uniqueness: true
>
> should it be uniqueue? arent there cities with same names? first we start
> with states, no prob there. But no value also i think.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/friendlyantz/who_is_america/pull/41#pullrequestreview-633054108>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ5F4DVG22MXIIR6KL46TZLTIVDGLANCNFSM42XN4VSQ>
> .
>

2021-04-14 12:25 UTC, StanislavLohtin approved these changes

2021-04-14 12:25 UTC, merged